// Fill out your copyright notice in the Description page of Project Settings.


#include "SelectedCharacter.h"

#include "Camera/CameraComponent.h"
#include "GameFramework/SpringArmComponent.h"
#include "EnhancedInputComponent.h"
#include "EnhancedInputSubsystems.h"

ASelectedCharacter::ASelectedCharacter()
{
	PrimaryActorTick.bCanEverTick = true;

	SpringArm = CreateDefaultSubobject<USpringArmComponent>(TEXT("SpringArm"));
	SpringArm->SetupAttachment(RootComponent);

	Camera = CreateDefaultSubobject<UCameraComponent>(TEXT("Camera"));
	Camera->SetupAttachment(SpringArm, USpringArmComponent::SocketName);
}

void ASelectedCharacter::BeginPlay()
{
	Super::BeginPlay();

	APlayerController* CharacterController = Cast<APlayerController>(Controller);
	if (CharacterController)
	{
		UEnhancedInputLocalPlayerSubsystem* Subsystem = ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>
														(CharacterController->GetLocalPlayer());

		if (Subsystem)
		{
			Subsystem->AddMappingContext(InputMappingContext, 0);
		}
	}
}

void ASelectedCharacter::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

void ASelectedCharacter::SetupPlayerInputComponent(class UInputComponent* PlayerInputComponent)
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);

	if (UEnhancedInputComponent* EnhancedInputComponent = Cast<UEnhancedInputComponent>(PlayerInputComponent))
	{
		EnhancedInputComponent->BindAction(MoveAction, ETriggerEvent::Triggered, this, &ASelectedCharacter::Move);

		EnhancedInputComponent->BindAction(JumpAction, ETriggerEvent::Started, this, &ASelectedCharacter::JumpStarted);
		EnhancedInputComponent->BindAction(JumpAction, ETriggerEvent::Completed, this, &ASelectedCharacter::JumpEnded);
		EnhancedInputComponent->BindAction(JumpAction, ETriggerEvent::Canceled, this, &ASelectedCharacter::JumpEnded);

		EnhancedInputComponent->BindAction(AttackAction, ETriggerEvent::Started, this, &ASelectedCharacter::Attack);

		// EnhancedInputComponent->BindAction(QuitAction, ETriggerEvent::Started, this, &ASelectedCharacter::QuitGame);
		
	}
}

void ASelectedCharacter::Move(const FInputActionValue& Value)
{
	float MoveActionValue = Value.Get<float>();

	FVector WorldDirection = FVector(1.f, 0, 0);
	AddMovementInput(WorldDirection, MoveActionValue);
	UpdateDirection(MoveActionValue);
}

void ASelectedCharacter::JumpStarted(const FInputActionValue& Value)
{
	Jump();
}

void ASelectedCharacter::JumpEnded(const FInputActionValue& Value)
{
	StopJumping();
}

void ASelectedCharacter::Attack(const FInputActionValue& Value)
{
}

void ASelectedCharacter::UpdateDirection(float MoveDirection)
{
	FRotator CurrentRotation = Controller->GetControlRotation();

	if (MoveDirection < 0.f)
	{
		if (CurrentRotation.Yaw != 180.f)
		{
			Controller->SetControlRotation(FRotator(CurrentRotation.Pitch, 180.f, CurrentRotation.Roll));
		}
	}
	else if (MoveDirection > 0.f)
	{
		if (CurrentRotation.Yaw != 0.f)
		{
			Controller->SetControlRotation(FRotator(CurrentRotation.Pitch, 0.f, CurrentRotation.Roll));
		}
	}
}
